### ISSUE TITLE
problem with colorama import

### ISSUE THREAD

**Issue by ghost** [yehia-mamdouh/XSSYA#5]
when i try to open xssya this problem appear 
linux@linux ~/XSSYA $ python xssya.py
Traceback (most recent call last):
  File "xssya.py", line 20, in <module>
    from colorama import Fore, Back, Style
ImportError: cannot import name Fore

**Comment by NetSec144** [comment]
Use this command when installing colorama for the first time:
$python setup.py install

Still haven't resolved the issue with no attribute 'PROTOCOL_SSLv3'

**Comment by yehia-mamdouh** [comment]
NetSec14, 
Remove the class from the script
class fake_ssl:
    wrap_socket = partial(ssl.wrap_socket, ssl_version=ssl.PROTOCOL_TLSv1)
httplib.ssl = fake_ssl
Remove this lines and it will work

**Comment by NetSec144** [comment]
Thanks Yehia.  However, I just downloaded and started working with your 2.0
version.
Thanks for your response!  2.0 is working correctly.

Shawn
